#!/usr/bin/env bash
# PR comment body + gh CLI. Lives outside the workflow YAML so parsers do not treat
# markdown [brackets], *asterisks, or :colons as YAML syntax.
set -u

if [ ! -s cursor-review.txt ]; then
  echo "No review output to post."
  exit 0
fi

{
  echo "## Cursor Agent Review"
  echo ""
  cat cursor-review.txt
  echo ""
  echo "*Generated by Cursor Agent workflow (.github/workflows/cursor-agent.yml)*"
} > pr-comment-body.txt

while IFS= read -r cid; do
  [ -z "$cid" ] && continue
  gh api -X DELETE "repos/${REPO}/issues/comments/${cid}" || true
done < <(gh pr view "$PR_NUM" --json comments -q '.comments[] | select(.body | startswith("## Cursor Agent Review")) | .databaseId' || true)

gh pr comment "$PR_NUM" --body-file pr-comment-body.txt
